### ISSUE TITLE
new format

### ISSUE THREAD

**Issue by termi111** [Chralt98/Kryptosteuertool#1]
Hi,

Thanks for sharing your project, good job.
Nevertheless, I try it with Binance, and the format is quite different to what the script expect.

1. my trade file is a csv file. (If I save the file into Excel, somehow the date are saved into Timestamp format and no more 'str' and this mess up the sorting.
binance_csv_handler.py line 57.
transactions = sorted(transactions, key=lambda tx: tx[0])
I then use read_csv from Pandas instead. This seems fine.

2. The columns are very different, I started to change the columns but then figure it out that this will probably not work for Trade.
    deposit_withdrawal_input_column_names = {'Date': 0, 'Coin': 1, 'Amount': 2, 'TransactionFee': 6, 'Address': 7,
                                             'TXID': 1, 'SourceAddress': 7, 'PaymentID': 7, 'Status': 3}
    trading_input_column_names = {'Date(UTC)': 0, 'Market': 1, 'Type': 2, 'Price': 3, 'Amount': 4,
                                  'Total': 5, 'Fee': 6, 'Fee Coin': 7}

This is the format I got for the "trade":

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MEDIAC~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MEDIAC~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

UTC_Time | Account | Operation | Coin | Change | Remark
-- | -- | -- | -- | -- | --
1/27/2021 14:34 | Spot | Deposit | EUR | xxxx|  
1/28/2021 20:47 | Spot | Buy | BTC | xxxxx |  
1/28/2021 20:47 | Spot | Transaction Related | EUR | xxxxx |  
1/28/2021 20:47 | Spot | Fee | BTC | xxxxx |  
1/28/2021 20:47 | Spot | Fee | BTC | xxxxx |  
1/28/2021 20:47 | Spot | Transaction Related | EUR | xxxxx |  
1/28/2021 20:47 | Spot | Buy | BTC | xxxxx |  

</body>

</html>

Which is quite different from a 1 line trade you had.

I am happy to support and help. I have relatively good python skills.
I just did not wanted to start from scratch if there is open source project out there.

Best regards,
Jonathan

**Comment by Chralt98** [comment]
Hey Jonathan,

feel free to change anything you want. It was just a side project and it's not meant to be used for production. CoinTracking is a good tool. They do a lot of updates.

Best regards,
Chralt
